CREATE TYPE "public"."warframe_class" AS ENUM('normal', 'prime', 'umbra');--> statement-breakpoint
CREATE TABLE "warframe" (
	"warframe_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"class" "warframe_class" NOT NULL,
	"lore" text,
	"base_health" double precision,
	"effective_health" double precision,
	"base_shield" double precision,
	"effective_shield" double precision,
	"base_armour" double precision,
	"effective_armour" double precision,
	"base_energy" double precision,
	"effective_energy" double precision,
	"base_ability_strength" double precision,
	"effective_ability_strength" double precision,
	"base_range" double precision,
	"effective_range" double precision,
	"base_duration" double precision,
	"effective_duration" double precision,
	"base_ability_efficiency" double precision,
	"effective_ability_efficiency" double precision,
	"base_sprint_speed" double precision,
	"effective_sprint_speed" double precision,
	"base_capacity" double precision,
	"effective_capacity" double precision,
	"max_passives" integer,
	"current_passives" jsonb,
	"max_abilities" integer,
	"current_abilities" jsonb,
	"max_mods" integer,
	"current_mods" jsonb,
	"max_aura_mods" integer,
	"current_aura_mods" jsonb,
	"max_exilus_mods" integer,
	"current_exilus_mods" jsonb,
	"max_arcanes" integer,
	"current_arcanes" jsonb,
	"max_shards" integer,
	"current_shards" jsonb,
	"weapons_loadout" jsonb
);
