ALTER TABLE IF EXISTS joinaunion.visit_info ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS joinaunion.visit_info ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.visit_info ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.visit_info ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
