import { logger } from '@helpers/logger';
import { db } from '@services/dbService';

/**
 * Seed default localizations (English and French)
 * PostgreSQL / CockroachDB compatible ON CONFLICT UPSERT
 */
await db.execute(`
    INSERT INTO localizations (slug, lang, language_name, text, codepage, direction, description) VALUES
        ('username', 'eng', 'English', 'Enter your username', 'UTF-8', 'ltr', 'Prompt asking user to enter their username'),
        ('username', 'fr', 'French', 'nom d''utilisateur', 'UTF-8', 'ltr', 'Invite demandant à l''utilisateur d''entrer son nom d''utilisateur'),
        ('home_welcome_title', 'eng', 'English', 'Welcome to the New App!', 'UTF-8', 'ltr', 'Homepage welcome title'),
        ('home_welcome_title', 'can_fr', 'French', 'Bienvenue sur la nouvelle application !', 'UTF-8', 'ltr', 'Titre de bienvenue'),
        ('home_welcome_description', 'eng', 'English', 'This is the new homepage center section. Below you will find links to various pages (formerly known as client apps).', 'UTF-8', 'ltr', 'Homepage welcome description'),
        ('home_welcome_description', 'can_fr', 'French', 'Voici la nouvelle section centrale. Vous trouverez ci-dessous les liens vers les différentes pages.', 'UTF-8', 'ltr', 'Description de bienvenue'),
        ('home_welcome_info', 'eng', 'English', 'Select a page from the icons below to learn more about us, contact us, or explore our services.', 'UTF-8', 'ltr', 'Homepage instructions'),
        ('home_welcome_info', 'can_fr', 'French', 'Sélectionnez une page parmi les icônes ci-dessous pour en savoir plus, nous contacter ou explorer nos services.', 'UTF-8', 'ltr', 'Instructions de la page d''accueil'),
        ('home_no_clients', 'eng', 'English', 'No clients available.', 'UTF-8', 'ltr', 'Empty clients message'),
        ('home_no_clients', 'can_fr', 'French', 'Aucun client disponible.', 'UTF-8', 'ltr', 'Message aucun client'),
        ('about_title', 'eng', 'English', 'About Us', 'UTF-8', 'ltr', 'About page title'),
        ('about_title', 'can_fr', 'French', 'À propos de nous', 'UTF-8', 'ltr', 'Titre de la page À propos'),
        ('about_description', 'eng', 'English', 'Learn more about our mission and team.', 'UTF-8', 'ltr', 'About page description'),
        ('about_description', 'can_fr', 'French', 'En savoir plus sur notre mission et notre équipe.', 'UTF-8', 'ltr', 'Description de la page À propos'),
        ('about_content_p1', 'eng', 'English', 'We are dedicated to building tools that empower users. Our platform provides a seamless experience for managing various client applications all in one place.', 'UTF-8', 'ltr', 'About page paragraph 1'),
        ('about_content_p1', 'can_fr', 'French', 'Nous nous consacrons à la création d''outils qui responsabilisent les utilisateurs. Notre plateforme offre une expérience fluide pour gérer diverses applications en un seul endroit.', 'UTF-8', 'ltr', 'À propos paragraphe 1'),
        ('about_content_p2', 'eng', 'English', 'Founded in 2026, our mission is to simplify the way you interact with digital services.', 'UTF-8', 'ltr', 'About page paragraph 2'),
        ('about_content_p2', 'can_fr', 'French', 'Fondée en 2026, notre mission est de simplifier vos interactions avec les services numériques.', 'UTF-8', 'ltr', 'À propos paragraphe 2'),
        ('about_nav_home', 'eng', 'English', 'Home', 'UTF-8', 'ltr', 'Home navigation button on About page'),
        ('about_nav_home', 'can_fr', 'French', 'Accueil', 'UTF-8', 'ltr', 'Bouton Accueil'),
        ('about_nav_contact', 'eng', 'English', 'Contact Us', 'UTF-8', 'ltr', 'Contact navigation button on About page'),
        ('about_nav_contact', 'can_fr', 'French', 'Contactez-nous', 'UTF-8', 'ltr', 'Bouton Contactez-nous'),
        ('contact_title', 'eng', 'English', 'Contact Us', 'UTF-8', 'ltr', 'Contact page title'),
        ('contact_title', 'can_fr', 'French', 'Contactez-nous', 'UTF-8', 'ltr', 'Titre de la page contact'),
        ('contact_description', 'eng', 'English', 'Get in touch with our team.', 'UTF-8', 'ltr', 'Contact page description'),
        ('contact_description', 'can_fr', 'French', 'Contactez notre équipe.', 'UTF-8', 'ltr', 'Description de la page contact'),
        ('contact_content_intro', 'eng', 'English', 'Have questions or feedback? We''d love to hear from you!', 'UTF-8', 'ltr', 'Contact page intro'),
        ('contact_content_intro', 'can_fr', 'French', 'Vous avez des questions ou des commentaires ? Nous aimerions avoir de vos nouvelles !', 'UTF-8', 'ltr', 'Introduction page contact'),
        ('contact_email', 'eng', 'English', 'Email: support@iworkhere.com', 'UTF-8', 'ltr', 'Contact email line'),
        ('contact_email', 'can_fr', 'French', 'Courriel : support@iworkhere.com', 'UTF-8', 'ltr', 'Ligne courriel de contact'),
        ('contact_phone', 'eng', 'English', 'Phone: +1 (555) 123-4567', 'UTF-8', 'ltr', 'Contact phone line'),
        ('contact_phone', 'can_fr', 'French', 'Téléphone : +1 (555) 123-4567', 'UTF-8', 'ltr', 'Ligne téléphone de contact'),
        ('contact_address', 'eng', 'English', 'Address: 123 Tech Lane, Innovation City', 'UTF-8', 'ltr', 'Contact address line'),
        ('contact_address', 'can_fr', 'French', 'Adresse : 123 Tech Lane, Innovation City', 'UTF-8', 'ltr', 'Ligne adresse de contact'),
        ('contact_nav_home', 'eng', 'English', 'Home', 'UTF-8', 'ltr', 'Home navigation button on Contact page'),
        ('contact_nav_home', 'can_fr', 'French', 'Accueil', 'UTF-8', 'ltr', 'Bouton Accueil'),
        ('contact_nav_about', 'eng', 'English', 'About Us', 'UTF-8', 'ltr', 'About navigation button on Contact page'),
        ('contact_nav_about', 'can_fr', 'French', 'À propos de nous', 'UTF-8', 'ltr', 'Bouton À propos'),
        ('sample_title', 'eng', 'English', 'Sample Client', 'UTF-8', 'ltr', 'Sample page title'),
        ('sample_title', 'can_fr', 'French', 'Client exemple', 'UTF-8', 'ltr', 'Titre client exemple'),
        ('sample_description', 'eng', 'English', 'A placeholder client application.', 'UTF-8', 'ltr', 'Sample client description'),
        ('sample_description', 'can_fr', 'French', 'Une application cliente d''exemple.', 'UTF-8', 'ltr', 'Description client exemple'),
        ('sample_placeholder_text', 'eng', 'English', 'This is just a placeholder', 'UTF-8', 'ltr', 'Sample placeholder text'),
        ('sample_placeholder_text', 'can_fr', 'French', 'Ceci est juste un espace réservé', 'UTF-8', 'ltr', 'Texte réservé exemple'),
        ('sample_btn_back_home', 'eng', 'English', 'Back to Home', 'UTF-8', 'ltr', 'Back to home button in sample client'),
        ('sample_btn_back_home', 'can_fr', 'French', 'Retour à l''accueil', 'UTF-8', 'ltr', 'Bouton retour accueil'),
        ('sample_btn_about', 'eng', 'English', 'About', 'UTF-8', 'ltr', 'About button in sample client'),
        ('sample_btn_about', 'can_fr', 'French', 'À propos', 'UTF-8', 'ltr', 'Bouton À propos'),
        ('sample_btn_contact', 'eng', 'English', 'Contact', 'UTF-8', 'ltr', 'Contact button in sample client'),
        ('sample_btn_contact', 'can_fr', 'French', 'Contact', 'UTF-8', 'ltr', 'Bouton Contact'),
        ('auth_client_title', 'eng', 'English', 'Sample Authenticated Client', 'UTF-8', 'ltr', 'Auth client title'),
        ('auth_client_title', 'can_fr', 'French', 'Client authentifié exemple', 'UTF-8', 'ltr', 'Titre client authentifié'),
        ('auth_client_description', 'eng', 'English', 'An authenticated client placeholder requiring user login.', 'UTF-8', 'ltr', 'Auth client description'),
        ('auth_client_description', 'can_fr', 'French', 'Un client authentifié nécessitant une connexion utilisateur.', 'UTF-8', 'ltr', 'Description client authentifié'),
        ('auth_client_logged_in_text', 'eng', 'English', 'You are logged in!', 'UTF-8', 'ltr', 'Auth client logged in message'),
        ('auth_client_logged_in_text', 'can_fr', 'French', 'Vous êtes connecté !', 'UTF-8', 'ltr', 'Message connecté'),
        ('auth_client_btn_back_home', 'eng', 'English', 'Back to Home', 'UTF-8', 'ltr', 'Back to home button in auth client'),
        ('auth_client_btn_back_home', 'can_fr', 'French', 'Retour à l''accueil', 'UTF-8', 'ltr', 'Bouton retour accueil'),
        ('auth_client_btn_about', 'eng', 'English', 'About', 'UTF-8', 'ltr', 'About button in auth client'),
        ('auth_client_btn_about', 'can_fr', 'French', 'À propos', 'UTF-8', 'ltr', 'Bouton À propos'),
        ('auth_client_btn_contact', 'eng', 'English', 'Contact', 'UTF-8', 'ltr', 'Contact button in auth client'),
        ('auth_client_btn_contact', 'can_fr', 'French', 'Contact', 'UTF-8', 'ltr', 'Bouton Contact'),
        ('host_header_title', 'eng', 'English', 'Join a Union!', 'UTF-8', 'ltr', 'Host shell header title'),
        ('host_header_title', 'can_fr', 'French', 'Rejoignez un syndicat !', 'UTF-8', 'ltr', 'Titre d''en-tête'),
        ('host_header_login', 'eng', 'English', 'Login', 'UTF-8', 'ltr', 'Host header login button'),
        ('host_header_login', 'can_fr', 'French', 'Connexion', 'UTF-8', 'ltr', 'Bouton Connexion'),
        ('host_header_logout', 'eng', 'English', 'Logout', 'UTF-8', 'ltr', 'Host header logout button'),
        ('host_header_logout', 'can_fr', 'French', 'Déconnexion', 'UTF-8', 'ltr', 'Bouton Déconnexion'),
        ('host_footer_copyright', 'eng', 'English', '© 2026 iworkhere', 'UTF-8', 'ltr', 'Host footer copyright text'),
        ('host_footer_copyright', 'can_fr', 'French', '© 2026 iworkhere', 'UTF-8', 'ltr', 'Droits d''auteur'),
        ('login_title', 'eng', 'English', 'Login', 'UTF-8', 'ltr', 'Login modal title'),
        ('login_title', 'can_fr', 'French', 'Connexion', 'UTF-8', 'ltr', 'Titre du modal de connexion'),
        ('login_identifier_placeholder', 'eng', 'English', 'Username or Email', 'UTF-8', 'ltr', 'Login identifier input placeholder'),
        ('login_identifier_placeholder', 'can_fr', 'French', 'Nom d''utilisateur ou courriel', 'UTF-8', 'ltr', 'Espace réservé identifiant'),
        ('login_password_placeholder', 'eng', 'English', 'Password', 'UTF-8', 'ltr', 'Login password placeholder'),
        ('login_password_placeholder', 'can_fr', 'French', 'Mot de passe', 'UTF-8', 'ltr', 'Espace réservé mot de passe'),
        ('login_submit_btn', 'eng', 'English', 'Login', 'UTF-8', 'ltr', 'Login submit button label'),
        ('login_submit_btn', 'can_fr', 'French', 'Se connecter', 'UTF-8', 'ltr', 'Bouton se connecter'),
        ('login_google_btn', 'eng', 'English', 'Login with Google', 'UTF-8', 'ltr', 'Login with Google button'),
        ('login_google_btn', 'can_fr', 'French', 'Se connecter avec Google', 'UTF-8', 'ltr', 'Bouton connexion Google'),
        ('login_google_loading', 'eng', 'English', 'Please wait...', 'UTF-8', 'ltr', 'Google login loading message'),
        ('login_google_loading', 'can_fr', 'French', 'Veuillez patienter...', 'UTF-8', 'ltr', 'Message attente Google'),
        ('login_register_link', 'eng', 'English', 'Register', 'UTF-8', 'ltr', 'Register link on login form'),
        ('login_register_link', 'can_fr', 'French', 'S''inscrire', 'UTF-8', 'ltr', 'Lien inscription'),
        ('login_eula_link', 'eng', 'English', 'View EULA', 'UTF-8', 'ltr', 'View EULA link on login form'),
        ('login_eula_link', 'can_fr', 'French', 'Voir le CLUF', 'UTF-8', 'ltr', 'Lien CLUF'),
        ('login_forgot_password_link', 'eng', 'English', 'Forgot password?', 'UTF-8', 'ltr', 'Forgot password link'),
        ('login_forgot_password_link', 'can_fr', 'French', 'Mot de passe oublié ?', 'UTF-8', 'ltr', 'Lien mot de passe oublié'),
        ('register_title', 'eng', 'English', 'Register', 'UTF-8', 'ltr', 'Register modal title'),
        ('register_title', 'can_fr', 'French', 'Inscription', 'UTF-8', 'ltr', 'Titre inscription'),
        ('register_username_placeholder', 'eng', 'English', 'Username', 'UTF-8', 'ltr', 'Register username input placeholder'),
        ('register_username_placeholder', 'can_fr', 'French', 'Nom d''utilisateur', 'UTF-8', 'ltr', 'Espace réservé nom d''utilisateur'),
        ('register_email_placeholder', 'eng', 'English', 'Email', 'UTF-8', 'ltr', 'Register email input placeholder'),
        ('register_email_placeholder', 'can_fr', 'French', 'Courriel', 'UTF-8', 'ltr', 'Espace réservé courriel'),
        ('register_password_placeholder', 'eng', 'English', 'Password', 'UTF-8', 'ltr', 'Register password placeholder'),
        ('register_password_placeholder', 'can_fr', 'French', 'Mot de passe', 'UTF-8', 'ltr', 'Espace réservé mot de passe'),
        ('register_eula_accept_prefix', 'eng', 'English', 'I accept the', 'UTF-8', 'ltr', 'EULA agreement prefix text'),
        ('register_eula_accept_prefix', 'can_fr', 'French', 'J''accepte le', 'UTF-8', 'ltr', 'Préfixe accord CLUF'),
        ('register_eula_link', 'eng', 'English', 'End User License Agreement', 'UTF-8', 'ltr', 'EULA link text'),
        ('register_eula_link', 'can_fr', 'French', 'Contrat de licence d''utilisateur final', 'UTF-8', 'ltr', 'Lien contrat CLUF'),
        ('register_submit_btn', 'eng', 'English', 'Register', 'UTF-8', 'ltr', 'Register submit button'),
        ('register_submit_btn', 'can_fr', 'French', 'S''inscrire', 'UTF-8', 'ltr', 'Bouton s''inscrire'),
        ('register_cancel_btn', 'eng', 'English', 'Cancel', 'UTF-8', 'ltr', 'Register cancel button'),
        ('register_cancel_btn', 'can_fr', 'French', 'Annuler', 'UTF-8', 'ltr', 'Bouton annuler'),
        ('password_reset_title', 'eng', 'English', 'Reset Password', 'UTF-8', 'ltr', 'Password reset title'),
        ('password_reset_title', 'can_fr', 'French', 'Réinitialiser le mot de passe', 'UTF-8', 'ltr', 'Titre réinitialisation'),
        ('password_reset_helper_initiate', 'eng', 'English', 'Enter your email address to receive a password reset token.', 'UTF-8', 'ltr', 'Password reset initiate helper'),
        ('password_reset_helper_initiate', 'can_fr', 'French', 'Entrez votre adresse courriel pour recevoir un jeton de réinitialisation.', 'UTF-8', 'ltr', 'Aide réinitialisation étape 1'),
        ('password_reset_email_placeholder', 'eng', 'English', 'Email address', 'UTF-8', 'ltr', 'Password reset email placeholder'),
        ('password_reset_email_placeholder', 'can_fr', 'French', 'Adresse courriel', 'UTF-8', 'ltr', 'Espace réservé courriel réinitialisation'),
        ('password_reset_btn_send_token', 'eng', 'English', 'Send Token', 'UTF-8', 'ltr', 'Send token button'),
        ('password_reset_btn_send_token', 'can_fr', 'French', 'Envoyer le jeton', 'UTF-8', 'ltr', 'Bouton envoyer jeton'),
        ('password_reset_helper_verify', 'eng', 'English', 'Enter the reset token sent to your email.', 'UTF-8', 'ltr', 'Password reset verify helper'),
        ('password_reset_helper_verify', 'can_fr', 'French', 'Entrez le jeton de réinitialisation envoyé à votre courriel.', 'UTF-8', 'ltr', 'Aide réinitialisation étape 2'),
        ('password_reset_token_placeholder', 'eng', 'English', 'Reset token', 'UTF-8', 'ltr', 'Password reset token input placeholder'),
        ('password_reset_token_placeholder', 'can_fr', 'French', 'Jeton de réinitialisation', 'UTF-8', 'ltr', 'Espace réservé jeton'),
        ('password_reset_btn_verify_token', 'eng', 'English', 'Verify Token', 'UTF-8', 'ltr', 'Verify token button'),
        ('password_reset_btn_verify_token', 'can_fr', 'French', 'Vérifier le jeton', 'UTF-8', 'ltr', 'Bouton vérifier jeton'),
        ('password_reset_btn_resend_token', 'eng', 'English', 'Resend Token', 'UTF-8', 'ltr', 'Resend token button'),
        ('password_reset_btn_resend_token', 'can_fr', 'French', 'Renvoyer le jeton', 'UTF-8', 'ltr', 'Bouton renvoyer jeton'),
        ('password_reset_helper_complete', 'eng', 'English', 'Choose a new password.', 'UTF-8', 'ltr', 'Password reset complete helper'),
        ('password_reset_helper_complete', 'can_fr', 'French', 'Choisissez un nouveau mot de passe.', 'UTF-8', 'ltr', 'Aide réinitialisation étape 3'),
        ('password_reset_new_password_placeholder', 'eng', 'English', 'New password', 'UTF-8', 'ltr', 'New password placeholder'),
        ('password_reset_new_password_placeholder', 'can_fr', 'French', 'Nouveau mot de passe', 'UTF-8', 'ltr', 'Espace réservé nouveau mot de passe'),
        ('password_reset_btn_reset_password', 'eng', 'English', 'Reset Password', 'UTF-8', 'ltr', 'Reset password submit button'),
        ('password_reset_btn_reset_password', 'can_fr', 'French', 'Réinitialiser le mot de passe', 'UTF-8', 'ltr', 'Bouton réinitialiser mot de passe'),
        ('password_reset_back_to_login', 'eng', 'English', 'Back to login', 'UTF-8', 'ltr', 'Back to login link'),
        ('password_reset_back_to_login', 'can_fr', 'French', 'Retour à la connexion', 'UTF-8', 'ltr', 'Lien retour connexion'),
        ('password_reset_close', 'eng', 'English', 'Close', 'UTF-8', 'ltr', 'Close link'),
        ('password_reset_close', 'can_fr', 'French', 'Fermer', 'UTF-8', 'ltr', 'Lien fermer'),
        ('eula_title', 'eng', 'English', 'End User License Agreement', 'UTF-8', 'ltr', 'EULA overlay title'),
        ('eula_title', 'can_fr', 'French', 'Contrat de licence d''utilisateur final', 'UTF-8', 'ltr', 'Titre CLUF'),
        ('eula_body_text', 'eng', 'English', 'This software is provided “as is”, without warranty of any kind, express or implied. By clicking Accept, you agree to be bound by the terms of this agreement.', 'UTF-8', 'ltr', 'EULA terms body text'),
        ('eula_body_text', 'can_fr', 'French', 'Ce logiciel est fourni « tel quel », sans garantie d''aucune sorte, expresse ou implicite. En cliquant sur Accepter, vous acceptez d''être lié par les termes de cet accord.', 'UTF-8', 'ltr', 'Texte CLUF'),
        ('eula_btn_accept', 'eng', 'English', 'Accept', 'UTF-8', 'ltr', 'Accept EULA button'),
        ('eula_btn_accept', 'can_fr', 'French', 'Accepter', 'UTF-8', 'ltr', 'Bouton accepter'),
        ('eula_btn_cancel', 'eng', 'English', 'Cancel', 'UTF-8', 'ltr', 'Cancel EULA button'),
        ('eula_btn_cancel', 'can_fr', 'French', 'Annuler', 'UTF-8', 'ltr', 'Bouton annuler'),
        ('email_verify_title', 'eng', 'English', 'Verify Email', 'UTF-8', 'ltr', 'Email verify title'),
        ('email_verify_title', 'can_fr', 'French', 'Vérifier le courriel', 'UTF-8', 'ltr', 'Titre vérification courriel'),
        ('email_verify_helper', 'eng', 'English', 'Enter the verification token from your email.', 'UTF-8', 'ltr', 'Email verify helper'),
        ('email_verify_helper', 'can_fr', 'French', 'Entrez le jeton de vérification reçu par courriel.', 'UTF-8', 'ltr', 'Aide vérification courriel'),
        ('email_verify_token_placeholder', 'eng', 'English', 'Verification token', 'UTF-8', 'ltr', 'Verification token placeholder'),
        ('email_verify_token_placeholder', 'can_fr', 'French', 'Jeton de vérification', 'UTF-8', 'ltr', 'Espace réservé jeton vérification'),
        ('email_verify_btn_verify', 'eng', 'English', 'Verify', 'UTF-8', 'ltr', 'Verify button'),
        ('email_verify_btn_verify', 'can_fr', 'French', 'Vérifier', 'UTF-8', 'ltr', 'Bouton vérifier'),
        ('email_verify_resend_label', 'eng', 'English', 'Resend token', 'UTF-8', 'ltr', 'Resend token label'),
        ('email_verify_resend_label', 'can_fr', 'French', 'Renvoyer le jeton', 'UTF-8', 'ltr', 'Étiquette renvoyer jeton'),
        ('email_verify_email_placeholder', 'eng', 'English', 'Email (optional)', 'UTF-8', 'ltr', 'Resend email placeholder'),
        ('email_verify_email_placeholder', 'can_fr', 'French', 'Courriel (facultatif)', 'UTF-8', 'ltr', 'Espace réservé courriel renvoi'),
        ('email_verify_btn_resend', 'eng', 'English', 'Resend', 'UTF-8', 'ltr', 'Resend button'),
        ('email_verify_btn_resend', 'can_fr', 'French', 'Renvoyer', 'UTF-8', 'ltr', 'Bouton renvoyer'),
        ('email_verify_back_to_login', 'eng', 'English', 'Back to login', 'UTF-8', 'ltr', 'Back to login link'),
        ('email_verify_back_to_login', 'can_fr', 'French', 'Retour à la connexion', 'UTF-8', 'ltr', 'Lien retour connexion'),
        ('email_verify_close', 'eng', 'English', 'Close', 'UTF-8', 'ltr', 'Close link'),
        ('email_verify_close', 'can_fr', 'French', 'Fermer', 'UTF-8', 'ltr', 'Lien fermer'),
        ('policy_blocked_title', 'eng', 'English', 'Access Restricted', 'UTF-8', 'ltr', 'Policy blocked title'),
        ('policy_blocked_title', 'can_fr', 'French', 'Accès restreint', 'UTF-8', 'ltr', 'Titre accès restreint'),
        ('policy_blocked_message', 'eng', 'English', 'Your account access has been restricted.', 'UTF-8', 'ltr', 'Policy blocked message'),
        ('policy_blocked_message', 'can_fr', 'French', 'L''accès à votre compte a été restreint.', 'UTF-8', 'ltr', 'Message accès restreint'),
        ('policy_blocked_details', 'eng', 'English', 'This may be due to policy violations. Please contact support for more information.', 'UTF-8', 'ltr', 'Policy blocked details'),
        ('policy_blocked_details', 'can_fr', 'French', 'Cela peut être dû à des violations de politique. Veuillez contacter le support.', 'UTF-8', 'ltr', 'Détails accès restreint'),
        ('policy_blocked_btn_logout', 'eng', 'English', 'Logout', 'UTF-8', 'ltr', 'Policy blocked logout button'),
        ('policy_blocked_btn_logout', 'can_fr', 'French', 'Déconnexion', 'UTF-8', 'ltr', 'Bouton déconnexion'),
        ('account_locked_title', 'eng', 'English', 'Account Locked', 'UTF-8', 'ltr', 'Account locked title'),
        ('account_locked_title', 'can_fr', 'French', 'Compte verrouillé', 'UTF-8', 'ltr', 'Titre compte verrouillé'),
        ('account_locked_message', 'eng', 'English', 'Your account has been temporarily locked.', 'UTF-8', 'ltr', 'Account locked message'),
        ('account_locked_message', 'can_fr', 'French', 'Votre compte a été temporairement verrouillé.', 'UTF-8', 'ltr', 'Message compte verrouillé'),
        ('account_locked_details', 'eng', 'English', 'This may be due to security reasons. Please try again later or contact support.', 'UTF-8', 'ltr', 'Account locked details'),
        ('account_locked_details', 'can_fr', 'French', 'Cela peut être pour des raisons de sécurité. Veuillez réessayer plus tard ou contacter le support.', 'UTF-8', 'ltr', 'Détails compte verrouillé'),
        ('account_locked_btn_logout', 'eng', 'English', 'Logout', 'UTF-8', 'ltr', 'Account locked logout button'),
        ('account_locked_btn_logout', 'can_fr', 'French', 'Déconnexion', 'UTF-8', 'ltr', 'Bouton déconnexion'),
        ('account_disabled_title', 'eng', 'English', 'Account Disabled', 'UTF-8', 'ltr', 'Account disabled title'),
        ('account_disabled_title', 'can_fr', 'French', 'Compte désactivé', 'UTF-8', 'ltr', 'Titre compte désactivé'),
        ('account_disabled_message', 'eng', 'English', 'Your account has been disabled.', 'UTF-8', 'ltr', 'Account disabled message'),
        ('account_disabled_message', 'can_fr', 'French', 'Votre compte a été désactivé.', 'UTF-8', 'ltr', 'Message compte désactivé'),
        ('account_disabled_details', 'eng', 'English', 'Please contact support for assistance.', 'UTF-8', 'ltr', 'Account disabled details'),
        ('account_disabled_details', 'can_fr', 'French', 'Veuillez contacter le support pour obtenir de l''aide.', 'UTF-8', 'ltr', 'Détails compte désactivé'),
        ('account_disabled_btn_logout', 'eng', 'English', 'Logout', 'UTF-8', 'ltr', 'Account disabled logout button'),
        ('account_disabled_btn_logout', 'can_fr', 'French', 'Déconnexion', 'UTF-8', 'ltr', 'Bouton déconnexion'),
        ('splash_title', 'eng', 'English', 'Welcome', 'UTF-8', 'ltr', 'Splash overlay title'),
        ('splash_title', 'can_fr', 'French', 'Bienvenue', 'UTF-8', 'ltr', 'Titre écran de démarrage'),
        ('splash_subtext', 'eng', 'English', 'Press continue to begin', 'UTF-8', 'ltr', 'Splash overlay subtext'),
        ('splash_subtext', 'can_fr', 'French', 'Appuyez sur continuer pour commencer', 'UTF-8', 'ltr', 'Sous-titre écran de démarrage'),
        ('splash_btn_continue', 'eng', 'English', 'Continue', 'UTF-8', 'ltr', 'Splash overlay continue button'),
        ('splash_btn_continue', 'can_fr', 'French', 'Continuer', 'UTF-8', 'ltr', 'Bouton continuer'),
        ('pause_title', 'eng', 'English', 'Paused', 'UTF-8', 'ltr', 'Pause overlay title'),
        ('pause_title', 'can_fr', 'French', 'En pause', 'UTF-8', 'ltr', 'Titre pause'),
        ('pause_subtext', 'eng', 'English', 'Tap to resume', 'UTF-8', 'ltr', 'Pause overlay subtext'),
        ('pause_subtext', 'can_fr', 'French', 'Touchez pour reprendre', 'UTF-8', 'ltr', 'Sous-titre pause')
    ON CONFLICT (slug, lang) DO UPDATE SET
        language_name = EXCLUDED.language_name,
        text = EXCLUDED.text,
        codepage = EXCLUDED.codepage,
        direction = EXCLUDED.direction,
        description = EXCLUDED.description;
`);

logger.log('🌱 localizations seed executed');
